#docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo (3.8)
version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
